/**
 * Filesystem layout for OpenBOT's local-first storage.
 *
 * Everything lives under `app.getPath('userData')` as plain JSON — no native
 * modules, no database. Paths resolve lazily so this module can be imported
 * before `app.whenReady()`.
 *
 *   <userData>/
 *     settings.json
 *     vm-secrets.json                 ← OS-encrypted bearer credentials
 *     backend-secrets.json            ← OS-encrypted model API credentials
 *     boxes/<vmId>/                    ← managed box workspace and guest runtime
 *     sessions/<id>.json
 *     bots/<id>.json
 *     routines/<id>.json
 *     memory/<botId>.json
 *     backups/<name>.<ts>.corrupt   ← quarantined unparseable files
 */

import { createHash } from 'node:crypto'
import { mkdirSync } from 'node:fs'
import { createRequire } from 'node:module'
import { join } from 'node:path'
import type { App } from 'electron'

const ensured = new Set<string>()

/**
 * Electron's `app`, resolved on first use instead of imported.
 *
 * A static `import { app } from 'electron'` is a load-time dependency on the
 * Electron runtime, and this module sits underneath the entire store — so every
 * module that reads or writes a document would be unloadable outside a running
 * app. The store tests exist to prove that a failed read never overwrites a good
 * file, and they cannot prove it if reaching the code means booting Electron.
 */
let cachedApp: App | null = null

function electronApp(): App {
  if (!cachedApp) cachedApp = (createRequire(import.meta.url)('electron') as { app: App }).app
  return cachedApp
}

/**
 * Root of all OpenBOT data.
 *
 * `OPENBOT_DATA_DIR` wins when it is set: it is what points the tests at a
 * throwaway directory, and what lets a portable install keep its data beside
 * itself. Unset — every real launch — this is Electron's own user-data path.
 */
export function dataRoot(): string {
  return process.env['OPENBOT_DATA_DIR'] || electronApp().getPath('userData')
}

/** `mkdir -p`, memoised, never throws. */
export function ensureDir(dir: string): string {
  if (ensured.has(dir)) return dir
  try {
    mkdirSync(dir, { recursive: true })
    ensured.add(dir)
  } catch (err) {
    console.error('[openbot/store] could not create directory', dir, err)
  }
  return dir
}

function subdir(name: string): string {
  return ensureDir(join(dataRoot(), name))
}

export function sessionsDir(): string {
  return subdir('sessions')
}

export function botsDir(): string {
  return subdir('bots')
}
export function groupsDir(): string { return subdir('groups') }
export function roomsDir(): string { return subdir('rooms') }

export function projectsDir(): string {
  return subdir('projects')
}

export function routinesDir(): string {
  return subdir('routines')
}

export function memoryDir(): string {
  return subdir('memory')
}

export function activityDir(): string { return subdir('activity') }
export function tasksDir(): string { return subdir('tasks') }

export function backupsDir(): string {
  return subdir('backups')
}

export function settingsFile(): string {
  ensureDir(dataRoot())
  return join(dataRoot(), 'settings.json')
}

export function vmSecretsFile(): string {
  ensureDir(dataRoot())
  return join(dataRoot(), 'vm-secrets.json')
}

export function backendSecretsFile(): string {
  ensureDir(dataRoot())
  return join(dataRoot(), 'backend-secrets.json')
}

export function mcpSecretsFile(): string {
  ensureDir(dataRoot())
  return join(dataRoot(), 'mcp-secrets.json')
}

export function boxesDir(): string {
  return subdir('boxes')
}

/** Create every directory up front, at startup. */
export function ensureAllDirs(): void {
  ensureDir(dataRoot())
  sessionsDir()
  botsDir()
  groupsDir()
  roomsDir()
  projectsDir()
  routinesDir()
  memoryDir()
  activityDir()
  tasksDir()
  backupsDir()
  boxesDir()
}

/**
 * Make an arbitrary id safe to use as a filename. Ids are generated by the
 * main process (uuid v4) but may also arrive from the renderer, so this is
 * defence in depth against `../` traversal and reserved characters.
 *
 * Sanitising is lossy — `a:b` and `a_b` both clean to `a_b`, and two long ids
 * can share a prefix — so a name that had to be rewritten carries a digest of
 * the id it came from. Two documents can then never land in one file and
 * silently overwrite each other. A uuid passes through untouched, so nothing
 * already on disk changes name.
 */
export function safeFileName(id: string): string {
  const cleaned = id
    .replace(/[^A-Za-z0-9._-]/g, '_')
    .replace(/^\.+/, '_')
    .slice(0, 120)
  if (cleaned === id) return cleaned
  const digest = createHash('sha256').update(id).digest('hex').slice(0, 12)
  return `${cleaned || '_'}-${digest}`
}
